### ISSUE TITLE
Переход на питон 3.10

### ISSUE THREAD

**Issue by rad-li** [vlmaksime/weather.gismeteo#17]
После обновления питона до версии 3.10 аддон перестал работать. Будете ли вы его обвновлять в соответствии с новыми правилами?

**Comment by vlmaksime** [comment]
Это проблема в зависимости SimplePlugin3. Вчера отправил запрос с исправлениями: [PR2180](https://github.com/xbmc/repo-scripts/pull/2180).
Можете подождать, пока примут изменения или обновить зависимость вручную по ссылке [SimplePlugin3 v3.0.6](https://github.com/vlmaksime/script.module.simpleplugin/releases/tag/v3.0.6)

**Comment by rad-li** [comment]
Отлично! Погода заработала. Спасибо.
