### ISSUE TITLE
Python exception when trying to configure locations

### ISSUE THREAD

**Issue by ErnstNeger** [vlmaksime/weather.gismeteo#18]
Hi,

when trying to configure locations (sometimes even on installation of the addon itself), I get entries the like in my [kodi.log](https://paste.kodi.tv/wafuwikupu.kodi).

Any idea what could be wrong?

**Comment by vlmaksime** [comment]
This error was caused by upgrading Python to version 3.10. It appears in the SimplePlugin3 add-on.
You can wait until the [PR2180](https://github.com/xbmc/repo-scripts/pull/2180) will be accepted or You can update the add-on manually [SimplePlugin3 v3.0.6](https://github.com/vlmaksime/script.module.simpleplugin/releases/tag/v3.0.6)

**Comment by ErnstNeger** [comment]
I'll wait for the PR to be accepted and report back. What I'm wondering though is: Like two days ago when I did the initial install and first run of Kodi, I got the plugin to work. I had other issues so I had to reinstall and then the plugin wasn't working anymore. I did not pay any attention to the Python version installed back then, do you know if the change happened in the last couple of days?

Thanks for your reply and best regards.

PS: If I wait for your commit to be accepted, will that update in Kodi automatically? I know too little about the Python scripts/extensions and how they're maintained in Kodi.

**Comment by vlmaksime** [comment]
> do you know if the change happened in the last couple of days?

I don't use Linux, but You are the third person who report this issue to me in this year.



> If I wait for your commit to be accepted, will that update in Kodi automatically?

Plugin will be updated automatically. If you install the plugin manually, automatic updates will not work.
