### ISSUE TITLE
LOGSEVERE and LOGNOTICE will deprecated in kodi/python addons

### ISSUE THREAD

**Issue by phunkyfish** [vlmaksime/weather.gismeteo#2]
Please replace with LOGFATAL and LOGINFO. They will be removed in a couple of weeks.

PR: https://github.com/xbmc/xbmc/pull/18346
Forum Post: https://forum.kodi.tv/showthread.php?tid=353818

**Comment by vlmaksime** [comment]
Thanks for the info.
I do not use these log levels in my add-on, they are used in the simpleplugin3 module
I will update it the next time I update my add-on

**Comment by phunkyfish** [comment]
Ok, I’ll also ping the author and see will they submit it as a script.module so you don’t need it locally in your addon if that’s possible.

**Comment by phunkyfish** [comment]
@romanvm ^^^

**Comment by vlmaksime** [comment]
@phunkyfish, romanvm stopped working on the module. Now I support this module.
The necessary edits have already been made in the module.
Simpleplugin3 module is not added to Kodi repository.

**Comment by phunkyfish** [comment]
Can it be added to the kodi repo? Any reason why it’s not? Just curious.

**Comment by vlmaksime** [comment]
> Any reason why it’s not? 

Because there are no add-ons in Kodi's repository that use it.
At the moment, only Gismeteo uses it. 
Alternatively, I will try to add the module to the official repository the next time I update Gismeteo.
