### ISSUE TITLE
Kodi Nexus update plan?

### ISSUE THREAD

**Issue by siliconhippy** [vlmaksime/weather.gismeteo#21]
Any estimate when there will be an update for Kodi Nexus?

**Comment by vlmaksime** [comment]
I made clean installation of Kodi 20.1 for Windows and installed Gismeteo plugin from official repository.
There is no any problems with plugin. 
Whats problems You have?

**Comment by siliconhippy** [comment]
Thanks for the response.
The plugin installs fine on my AlexElec.tv x86 11.1.2 ( Kodi 20.1) with the Arctic Zephr Reloaded skin.

However it does not allow me to switch cities, or show beyond daily temperature.

No problems with Arctic Zephr on Kodi 18 ( AE 3.3.5 arm tv box), or, iirc, on Matrix ( AE x86.)

**Comment by vlmaksime** [comment]
Probably, there is problem with the Arctic Zephr Reloaded skin.
Try to switch the cities at Estuary skin

**Comment by siliconhippy** [comment]
![IMG_20230329_013551](https://user-images.githubusercontent.com/42253841/228436588-5e757166-395e-4aea-8564-36fc7219d7ea.jpg)

![IMG_20230329_014122](https://user-images.githubusercontent.com/42253841/228437422-9a768195-a62b-43c2-873b-983771c87303.jpg)

On AE 11.1.2 OX x86 Kodi 20.1:
A. With Estuary too, I cannot switch default city ( Can't go to the city tab.) 
But I do see a 7 day forecast and also a 3 hourly forecast, 11am to 11pm next day.

B. On Arctic Zephr Reloaded, I can see default city with 7 day forecast. But can't change city, and no hourly !

**Comment by vlmaksime** [comment]
I don't use Arctic Zephr skin, so I don't know, how it's works.

At Estuary skin You should press Enter button on "Weather" string at side menu. This action should open Weather page, where You can change current city by pressing Enter button at the top widget.
![kodi](https://user-images.githubusercontent.com/11209490/228604873-35cf0cf3-1d4e-4ae0-91b9-1059890baaaa.gif)

**Comment by siliconhippy** [comment]
On Estuary skin , I did press Enter on side menu to display Weather. Then I tried to move cursor to the City menu at top, but I cannot go to that menu !

In any case these multi weather guys seem to have updated to Nexus. See last few comments. Same problem initially- working on Windows and Android, not on Libreelec or Coreelec:

 https://forum.kodi.tv/archive/index.php?thread-352028-14.html

Edit: Tried multi weather app instead. I see no change in look and feel ! So looks like this is a fork of your project, or the other way around.

And unluckily, same problems as above ! No improvement over your addon.

Edit 2: Problem solved for AZR skin, very kludgy way !

A. In AZR skin, click on Weather menu
B. Then highlight a day
C. Click Enter, get a bigger days display
D. Now click Up arrow. Get a menu from which you can change ( "refresh") cities and other items
E. Use Back button to go back.

However still  no luck changing cities in Estuary skin with AlexElec ( CoreElec fork.)

Anyway thank you for engaging ...😸
