### ISSUE TITLE
Added Dutch Translation

### ISSUE THREAD

**Issue by Miniontoby** [vlmaksime/weather.gismeteo#26]
Hi,

I added Dutch translations.

See the PR's here: 
#23  #24  #25 

I did three Pull Request, since there are three different branches...

**Comment by Miniontoby** [comment]
Thanks for adding it!

Btw, May I know why the settings.xml is not updated?

**Comment by vlmaksime** [comment]
At settings listed languages, which supported by service API. There is no Dutch language at supported languages.

**Comment by Miniontoby** [comment]
I could also (try to) translate the service API...

**Comment by vlmaksime** [comment]
We do not have the ability to edit the weather provider service API
