### ISSUE TITLE
Missing option/auto-defaulting to temperature scale

### ISSUE THREAD

**Issue by stdedos** [vlmaksime/weather.gismeteo#3]
I am in EU, have added EU cities, and still I am getting Fahrenheit temperatures

**Comment by vlmaksime** [comment]
Hello.
You have to change the temperature units in Settings - Interface - Regional.
You may also need to change the speed units.

**Comment by stdedos** [comment]
Okay, I saw what the problem is: I did that on the same "Kodi session", and the extension did not update.

If it's possible:
* Check that settings are updated on-the-fly
* Add a link to "Change Units in Settings here"

**Comment by vlmaksime** [comment]
Just checked it out. Temperature units were updated in the add-on immediately after changing the settings. It's Kodi responsible for this.
As for opening the regional settings window from the add-on settings, I'll see what I can do.

**Comment by stdedos** [comment]
I don't know what happened then. 😕 
I am pretty sure, since I was looking for a "refresh weather data" action, and I couldn't find any either.
