### ISSUE TITLE
Always show the city name

### ISSUE THREAD

**Issue by stdedos** [vlmaksime/weather.gismeteo#4]
If I have multiple cities, and I want to cycle among them, it is much more convenient to immediately show the city's name, instead of waiting for it until weather data are fetched and displayed.

**Comment by vlmaksime** [comment]
I guess I can set city name from the saved setting before calculating the weather values

**Comment by vlmaksime** [comment]
I tried setting the city name at the beginning of the script execution, but nothing changed. Kodi updates the information only after the end of the script execution.

**Comment by stdedos** [comment]
No - that would have to be a secondary execution.

If too complex, then it cannot be done otherwise.
